apiVersion: v1
kind: Secret
metadata:
  name: myapp-rabbitmq-secret
  namespace: myapp
type: Opaque
stringData:
  uri: amqp://192.168.0.3:5672
  port: "5672"
  username: appuser3
  password: qwerty
  vhost: /
