apiVersion: v1
kind: Secret
metadata:
  name: myapp-rabbitmq-secret
  namespace: myapp
type: Opaque
stringData:
  host: host.docker.internal
  port: "5672"
  username: guest
  password: guest
  vhost: /
